spring:
  application:
    name: geo-service
  datasource:
    url: jdbc:postgresql://localhost:5432/stations
    username: postgres
    password:
  jpa:
    show-sql: on
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

server:
  port: 8181